// GENERADO por scripts/import-org-tags.mjs el 2026-09-29. No editar a mano.
//
// Tags por speaker copiados del TAGS_MAP de LABITCONF-speakers/web.html,
// resueltos por nombre normalizado. Es un puente hasta que la organización
// cargue la columna `tags` en la planilla: si esa columna existe, gana ella.
// Descartados por número ambiguo o inexistente: 57 (no existe), 219 (alejandra guajardo / gaucho paisano), 221 (ramiro marra / tomas cristal), 222 (carlos maslaton / marcelo edgardo de vincenzi zemborain).

export const ORG_TAGS_SNAPSHOT: Record<string, string> = {
  "adolfo raed": "Legal,Bitcoin",
  "adrian bernabeu": "Adopcion",
  "adrian trevino": "Bitcoin",
  "agostina macagno": "Emprendimiento",
  "agus rizzo": "IA",
  "agustina paez": "Tecnico",
  "aldana celeste fernandez": "Finanzas",
  "alejandro narancio": "Bitcoin",
  "alessandro cecere": "Bitcoin",
  "alexandra navarro": "Mining",
  "alfa ley": "Tecnico",
  "alfredo carrillo mendoza": "Privacidad",
  "alfredo roisenzvit": "Adopcion,Educacion",
  "alonso moyano": "Bitcoin",
  "ana ojeda": "Adopcion",
  "angel jose": "Bitcoin",
  "anna datsenko": "Tecnico",
  "ariel aguilar": "Educacion",
  "ariel rajovitzky": "Bitcoin",
  "arley lozano": "Legal,Tecnico",
  "ary frischman": "Bitcoin",
  "axel arellano": "Custodia",
  "axel becker": "Custodia",
  "axel camargo": "Bitcoin",
  "axel jutoran": "Custodia",
  "aylen fuente": "Bitcoin",
  "benjamin barlow": "Legal",
  "birkan kayadibi": "Educacion",
  "borja martel seward": "Finanzas,IA",
  "bruno vaccotti": "Tecnico",
  "bryan aguilar": "IA",
  "camila da silva tabares": "IA",
  "camila soria": "Tecnico",
  "camilo jdl": "IA",
  "carla torazzi": "Custodia",
  "catrya catrya": "Bitcoin",
  "chris guida": "Institucional",
  "christian durand": "IA",
  "christopher shei": "Adopcion",
  "cinthya franca": "IA",
  "claudia ramirez d auria": "Educacion,Adopcion",
  "damian marsero": "Emprendimiento",
  "damian silva": "Educacion",
  "daniel andres pelaez": "IA",
  "dario nieto": "Bitcoin",
  "david zell": "Institucional",
  "delfina elizalde": "Tecnico",
  "diana gardene aramayo poquiviqui": "Educacion",
  "diego brito": "Bitcoin",
  "diego coria": "IA",
  "diego gurpegui": "Mining",
  "dusan matuska": "Bitcoin",
  "eduardo rigon": "Legal",
  "elisandro santos": "IA,Tecnico",
  "emily ruiz": "Bitcoin",
  "eugenia tambussi": "Legal",
  "ezequiel gorbatik": "IA",
  "ezequiel olgiatti": "Emprendimiento",
  "fabrizio bianchi": "Emprendimiento",
  "facundo poveda": "IA,Finanzas",
  "federico brom": "Legal",
  "federico goldberg": "IA",
  "felipe duran": "Bitcoin",
  "fernanda rocha": "Institucional,Custodia",
  "fierillo f": "Privacidad",
  "francisco jose coronel calvet": "Finanzas",
  "franco maffoni": "Finanzas",
  "franco villabona": "Adopcion",
  "frank moreira": "Bitcoin",
  "franz tunez": "Bitcoin",
  "gabriel kurman": "Adopcion",
  "gabriela battiato": "IA,Tecnico",
  "gabriela serkin": "Emprendimiento",
  "german gimenez": "Custodia",
  "german welchli": "Adopcion",
  "giacomo zucco": "Bitcoin",
  "giovanni santostasi": "Bitcoin",
  "gonzalo nazar de la vega": "Emprendimiento",
  "gonzalo zaccardi": "Finanzas",
  "graeme moore": "Legal",
  "guille schettino": "Mining",
  "guillermo escudero": "Bitcoin",
  "guillermo peyrano": "Legal",
  "ivan cristini": "IA",
  "ivan kaleja": "Tecnico,Privacidad",
  "ivan paz chain": "Tecnico",
  "jan marvan": "Bitcoin",
  "jania muller": "Legal",
  "jaqui rodriguez": "Emprendimiento",
  "javier bastardo": "Tecnico",
  "javier forte": "Bitcoin",
  "javier garcia sanchez": "Bitcoin",
  "javier mateos": "IA",
  "jeremias souto": "Bitcoin,Educacion",
  "jeronimo ferrer": "Adopcion",
  "jessica soledad caceres": "Bitcoin",
  "jhon martinez": "Adopcion",
  "jimena vallone": "Adopcion",
  "joaquin giorgis": "IA",
  "jonathan bravetti": "Custodia",
  "jonathan chagerben": "Bitcoin,Finanzas,Adopcion",
  "jose drybit": "Emprendimiento",
  "jose landaeta": "Finanzas",
  "jose luis del palacio": "Custodia,Legal,Privacidad",
  "jose noriega": "Bitcoin",
  "juan carlos gutierrez": "Legal",
  "juan fridenberg": "Mining",
  "juan jose lizarraga": "Bitcoin",
  "juan manuel caceres": "Educacion",
  "juan manuel campos alvarez": "Mining",
  "juan manuel dominguez": "Mining",
  "juan sebastian landy rios": "Emprendimiento",
  "juan soria": "Bitcoin",
  "julia socorro": "Bitcoin",
  "julian colombo": "Bitcoin",
  "julian drangosch": "Bitcoin",
  "julian landerreche": "Institucional",
  "julian liniger": "Mining",
  "karina nunez": "Educacion",
  "kristopher panana": "Educacion",
  "leandro conti": "Tecnico,Educacion",
  "leandro fernandez": "Emprendimiento",
  "leandro furundarena": "Adopcion",
  "leon acosta": "Educacion",
  "leopoldo bebchuk": "Custodia",
  "lina escarraga": "Legal",
  "lorena martin": "Bitcoin",
  "lorena ortiz": "IA",
  "lucas abihaggle": "IA",
  "lucas ontivero": "Tecnico",
  "lucia barreto": "Bitcoin",
  "luis eduardo herrera": "Emprendimiento",
  "luis j canessa": "Finanzas",
  "luis rodriguez": "Adopcion",
  "lunaticoin": "Adopcion",
  "malena martin": "IA",
  "manuel ferrari": "Bitcoin",
  "marco esparza": "Adopcion",
  "marcos zocaro": "Bitcoin,Privacidad",
  "maria jazmin gervasio d ambra": "Bitcoin",
  "marisa mancuello": "Mining",
  "matias armandola": "Legal",
  "matias mathey": "Bitcoin",
  "mauricio castillo": "IA",
  "mauricio tovar": "IA",
  "maximiliano perez": "Adopcion,Educacion",
  "melisa barrantes": "Educacion",
  "michel cohen": "Emprendimiento",
  "miguel fortuna": "Legal",
  "miguel klagges": "Finanzas",
  "milos zivkovic": "Adopcion",
  "nahuel maeso": "Emprendimiento",
  "nicolas madoery": "Tecnico",
  "nicolas schteinschraber": "Emprendimiento",
  "niko seguro": "Bitcoin",
  "pablo sebastian gomez": "Tecnico",
  "pauli rinaldi": "Educacion",
  "pavol luptak": "Legal",
  "pedro e gutierrez q": "Mining",
  "pedro meinberg fadida": "Tecnico",
  "pedro rey puma": "Finanzas",
  "pedro solimano": "Bitcoin",
  "pilar sanchez ordonez": "Privacidad",
  "ramiro carnicer souble": "IA",
  "ramiro larrouyet": "Adopcion",
  "ricardo espinosa": "Bitcoin",
  "richard bitzhan": "Custodia",
  "richard byworth": "Institucional",
  "rodolfo andragnes": "Custodia,Educacion",
  "rodrigo castaneda": "IA",
  "saifedean ammous": "Educacion,Privacidad",
  "salome arboleda": "IA",
  "samuel tome": "Institucional",
  "santiago guzman": "Adopcion",
  "santiago mora": "Mining",
  "santiago nehuen andrade messali": "Privacidad",
  "sara plencovich": "Bitcoin",
  "sebastian chuffer": "Mining",
  "sebastian ignacio cordero": "Emprendimiento",
  "sebastian schanz": "Finanzas",
  "sergio demian lerner": "Bitcoin",
  "sergio jacobo": "Bitcoin",
  "sergio omar aguilera": "Legal",
  "sofia soledad cardozo": "Bitcoin",
  "stephie cherni": "Adopcion",
  "tracy estefania loza maldonado": "IA",
  "valentin popescu": "IA",
  "valentino malacalza": "Legal",
  "veronica alegre": "Emprendimiento",
  "walter torres": "Bitcoin",
  "wesley andrade": "Bitcoin",
  "yaccel alexander soto lopez": "Finanzas",
  "yuri da silva barbosa": "Custodia",
};
